"""initial

Revision ID: 3bc156a26cb9
Revises:
Create Date: 2025-12-13 21:05:29.692795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3bc156a26cb9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('roles', postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column('langflow_user_id', sa.String(length=255), nullable=True),
        sa.Column('langflow_project_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    )
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_index(op.f('user_username_idx'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_username_idx'), table_name='user')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
