#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Backend database and user
    CREATE DATABASE ${BACKEND_DB};
    CREATE USER ${BACKEND_USER} WITH ENCRYPTED PASSWORD '${BACKEND_PASSWORD}';
    GRANT CONNECT ON DATABASE ${BACKEND_DB} TO ${BACKEND_USER};

    -- Langflow database and user
    CREATE DATABASE ${LANGFLOW_DB};
    CREATE USER ${LANGFLOW_USER} WITH ENCRYPTED PASSWORD '${LANGFLOW_PASSWORD}';
    GRANT CONNECT ON DATABASE ${LANGFLOW_DB} TO ${LANGFLOW_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${BACKEND_DB}" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE ${BACKEND_DB} TO ${BACKEND_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${BACKEND_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${BACKEND_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${LANGFLOW_DB}" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE ${LANGFLOW_DB} TO ${LANGFLOW_USER};
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${LANGFLOW_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${LANGFLOW_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${LANGFLOW_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${LANGFLOW_USER};
EOSQL

echo "Databases and users initialized successfully"

